Better error handling in Repos
In current version, we have "catch-all" error handling that efficiently hides the actual
reason for the error. It's not possible to understand the reason for error, for example,
when IP Access List is used. This patch improves the error reporting:

Without patch

```
Error: RuntimeError: Can't find repo ID for /Repos/user/repo
```

With patch:

```
Error: RuntimeError: Error fetching repo ID for /Repos/user/repo: HTTP code: 403, Unauthorized access to Org: 1234567890
```